spring.protocol=http
spring.host=localhost
spring.port=8080

python.protocol=http
python.host=localhost
python.port=8000

spring.base_url=http://localhost:8080
python.base_url=http://localhost:8000

results.dir=../resultados
connect.timeout.ms=10000
response.timeout.ms=30000
